### ISSUE TITLE
Failed to write large text

### ISSUE THREAD

**Issue by ImSejin** [javaxcel/javaxcel-core#7]
```text
Exception in thread "main" java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32767 characters
	at org.apache.poi.ss.usermodel.CellBase.checkLength(CellBase.java:292)
	at org.apache.poi.ss.usermodel.CellBase.setCellValue(CellBase.java:273)
	at com.github.javaxcel.out.core.impl.ModelWriter.createBody(ModelWriter.java:347)
	at com.github.javaxcel.out.core.AbstractExcelWriter.write(AbstractExcelWriter.java:122)
```

**Comment by ImSejin** [comment]
Limit on the length of cell contents results from Excel structure, not javaxcel.
That's not what I can deal with, so this issue is not bug.
